### ISSUE TITLE
Fresh install in new Rails 4 app.. 'Uncaught SyntaxError: Unexpected token :'

### ISSUE THREAD

**Issue by PDaily** [alchapone/polymer-rails#30]
Like the title says, decided to give this a swing and see how well it performs.

Generated a new Rails 4 app, added polymer-rails to my gem and ran a bundle install.

After adding the html_import_tag into my main layout and refreshing the page gives me the Syntax error in the web console.

Even tried comparing this with your example and everything matches up, though I noticed you had removed Spring from your Gemfile.

Any idea what I may be doing wrong here?

EDIT: You can reference the branch I made here: https://github.com/PDaily/Technician/tree/polytest

**Comment by nielsen** [comment]
I'm having the same problem with 0.2.5 -- it looks like the gem is no longer pulling in webcomponents.js (the example app is using 0.2.4).

**Comment by alchapone** [comment]
Example app works fine with 0.2.5, I've just updated it. @PDaily it has to be related to poymer-core-rails, it is more unstable and causes multiple issues.

**Comment by Vitalijus** [comment]
I'm having the same problem with 0.2.8. Error: You tried to use polymer without loading it first.

**Comment by alchapone** [comment]
Make sure that polymer.js should be the first script included into your page. This is the reason in 90% cases, why you get this error 'You tried to use polymer without loading it first'

**Comment by Vitalijus** [comment]
In your README paragraph "Creating a component"  you are asking "Add your component to manifest file after requiring webcomponents". For me this part was misleading, because it says to add component-name after webcomponents in application.js:
//= require polymer/webcomponents
//= require component-name/component-name

That why it didn't worked for me. So I added component-name to components/application.html.erb and it works now:
//= require polymer/polymer
//= require component-name/component-name

**Comment by alchapone** [comment]
Oh, yes. There was an error in readme (I might have introduced it during renaming `platform` to `webcomponents`). Sure you don't need to include `webcomponents` into your html manifest. First line should be `//= require polymer/polymer`
