### ISSUE TITLE
web-animations-next-lite.min.js.map Not Found

### ISSUE THREAD

**Issue by Urbanviking** [alchapone/polymer-rails#39]
Hi,
I am wondering if there are others that have seen this issue.

I am getting this message:
  GET http://localhost:3000/assets/web-animations-next-lite.min.js.map 404 (Not Found)

Thanks

**Comment by Urbanviking** [comment]
The workaround is to do a manual install.

**Comment by shawntoffel** [comment]
Looked into it a bit.

This sounds related to polymer-core-rails or polymer-paper-rails. Both gems contain core-animation which imports the web-animations-next-lite.min.js file.  I was able to reproduce this error in the Chrome debug console when running rails in development mode with the polymer-paper-rails gem. The error shouldn't show up in production mode.

Source-map files are used by the browser to map between the minified js and original (useful when debugging). 

The error is caused by this line at the bottom of the minified js:

    //# sourceMappingURL=web-animations-next-lite.min.js.map

This is included inline with the rest of the components in application.html.  As far as I know source-map support for rails (sprockets) is still a work in progress. Therefore, I believe the error will still exist if we simply include the map files in the gem assets. Removing the line is also less than ideal since the components are updated via bower.

**Comment by Urbanviking** [comment]
Thank you for quick reply.

###### My workaround

* Download directly from polymer element that included web-animation-js.
* Place the downloaded web-animation-js folder in either app/lib/assets or app/vendor/assets.
* Add  `//= require web-animations-js` to app/assets/javascripts/application.js.

It might be helpful for others to highlight this on Installation page until the issue has been resolved.

**Comment by Urbanviking** [comment]
Closed as the issue isn't with polymer-rails.
