### ISSUE TITLE
undefined method html_import_tag

### ISSUE THREAD

**Issue by xcaptain** [alchapone/polymer-rails#46]
I've `gem 'polymer-rails'` in my Gemfile 
`<%= html_import_tag 'application'%>` in my layout file

`bundle show | grep polymer` gets `polymer-rails (1.0.3)`

then I got this error
```
undefined method `html_import_tag' for #<#<Class:0x000000038394a8>:0x00000003838620>
```
I tried `bundle clean` to reinstall all the gems but it just doesn't work, is it a bug or if I can require this gem manually?

**Comment by alchapone** [comment]
Is it a new rails app, or you're adding gem to project with some codebase?

**Comment by xcaptain** [comment]
No, it's not a new app, I was using bootstrap template and these days I want to try polymer, so I found this repo. Do you have any good suggestions to debug this issue?

**Comment by alchapone** [comment]
There's a hint in your error - `html_import_tag for #<#<Class:0x000000038394a8>:0x00000003838620>`
Which means that `html_import_tag` is being called not in the view context, otherwise you would see `html_import_tag for ActionView::`. This might be caused by some html processors like `haml`, `slim` or whatever you may use.

**Comment by xcaptain** [comment]
problem solved, `polymer-rails` gem has conflict with `materialize-sass` and I removed `gem 'materialize-sass'` from my Gemfile then things went ok, Thank you so much.
